# Default values for custom-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  name: fleetman-container
  dockerRepo: richardchesterwood
  port: 80
  dev: true # defines if environment is devlopment

service:
  name: fleetman-service
  port: 80
  targetPort: 80

deployment:
  name: fleetman-deployment

ingress:
  name: fleetman-ingress
  host: my-fleetman.example.com
  port: 80