# Default values for custom-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  name: fleetman-container
  image: richardchesterwood/k8s-fleetman-helm-demo:v1.0.0-dev
  port: 80

service:
  name: fleetman-service
  port: 80
  targetPort: 80

deployment:
  name: fleetman-deployment

ingress:
  name: fleetman-ingress
  host: my-fleetman.example.com
  port: 80




resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
