apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.dockerRepo | default "richardchesterwood" | lower }}/k8s-fleetman-helm-demo:v1.0.0{{ if .Values.container.dev }}-dev{{ end }}
        ports:
         - containerPort: {{ .Values.container.port }}